swagger: '2.0'

# Document metadata
info:
  version: "1.1.1.BA"
  title: Gyroscope tests
  description: |
    This file defines API for Fyysikkokilta handwaving measurement service.
  termsOfService:
  contact:
    name: Eemil Visakorpi
    url: http://fyysikkokilta.fi
# Paths
paths:
  /Fyssa/Bailu:
    get:
      description: |
        Get current config and temperature. 
      responses:
        200:
         schema:
            $ref: '#/definitions/FyssaBailuResponse'
        204:
          description: Source unavailable.
    put:
      description: Prepare to measure party data for a configured amount of time.
              Get a Data value.
      parameters:
        - name: fyssaBailuConfig
          in: body
          description: New configurations for the test.
          required: true
          schema:
            $ref: '#/definitions/FyssaBailuConfig'
      responses:
        200:
          description: Success
        204:
          description: Measurement source is unavailable
  /Fyssa/Bailu/Stop:
    get:
      description: Get current status and stop measuring. Time shows how much scanning is left.
      responses:
        200:
         schema:
            $ref: '#/definitions/FyssaBailuResponse'
        204:
          description: Unavailable
  /Fyssa/Debug/Subscription:
    post:
      description: Get all kinds of debugging data.
      responses:
        200:
          description: Succeeded.
        x-std-errors:
          description: See common error codes http://developer.suunto.com/api/std-errors#subscribe
        x-notification:
          schema:
            description: Debug values
            $ref: '#/definitions/DebugStuff'
    delete:
      description: Unsubscribe
      responses:
        200:
          description: Operation completed successfully
        x-std-errors:
          description: See common error codes http://developer.suunto.com/api/std-errors#unsubscribe
definitions:
  FyssaBailuConfig:
    type: object
    required:
      - time
      - threshold
    properties:
      time:
        description: |
          Time for measuring in minutes
        type: integer
        format: uint32
      threshold:
        description: Smallest temperature in celcius to be considered partyable
        type: integer
        format: uint32
  FyssaBailuResponse:
    type: object
    required:
      - time
      - threshold
      - curTemp
      - seenDevices
    properties:
      time:
        description: |
          Time spent partying in seconds.
        type: integer
        format: uint32
      threshold:
        description: Smallest temperature in celcius to be considered partyable
        type: integer
        format: uint32
      curTemp:
        description: Temperature in celcius
        type: number
        format: float
      seenDevices:
        description: Most scanned devices partying
        type: integer
        format: uint16    
  DebugStuff:
    description: Describes debug stuff.
    required:
      - temperature
      - isPartying
      - minuteAccAvr
      - hourAccAvr
      - runningTime
      - partyScore
    properties:
      temperature:
        type: number
        format: float
      isPartying:
        type: boolean
      minuteAccAvr:
        type: number
        format: float
      hourAccAvr:
        type: number
        format: float
      runningTime:
        type: integer
        format: uint32
      partyScore:
        type: integer
        format: uint32 

